[package]
name = "pixel-sorter-better"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
image = "0.24.8"
egui = "0.26.2"
eframe = "0.26.2"
rayon = "1.8.1"
flume = "0.11.0"